"""Meal logging, deterministic estimation, saved plans (read side).

Endpoints
    POST   /api/meals/estimate  -> {"items": [{"name", "quantity"?|"grams"?}]}
                                   deterministic FoodTable estimate (no LLM, not saved)
    POST   /api/meals           -> same body + "meal_type"? -> estimate AND log it
    GET    /api/meals?days=7    -> logged meals, oldest first
    DELETE /api/meals/<id>      -> remove a log entry
    GET    /api/foods/search?q= -> food table search (autocomplete)
    GET    /api/meal-plans      -> saved plans (generated by the Meal Planner agent)
    DELETE /api/meal-plans/<id> -> remove a saved plan

Free-text analysis ("today I ate 2 rotis and dal") is the Meal Analyzer
agent's job; it calls the same estimator with the items it extracts.
"""

from __future__ import annotations

from flask import Blueprint, request
from flask_login import login_required

from nutrimind.exceptions import ValidationError
from nutrimind.extensions import db
from nutrimind.models import MealLog, MealPlan
from nutrimind.routes import current_user_id, ok
from nutrimind.services.nutrition_service import get_food_table
from nutrimind.utils.validators import (
    sanitize_text,
    validate_meal_items,
    validate_meal_type,
    validate_range,
)

meals_api = Blueprint("meals_api", __name__, url_prefix="/api")


@meals_api.before_request
@login_required
def _require_login():
    """Default-deny: every endpoint in this blueprint needs a session.

    Applied at the blueprint rather than per route so that adding an
    endpoint cannot accidentally expose one account's data to another.
    """


def _estimate_from_request() -> tuple[dict, list[dict]]:
    data = request.get_json(silent=True) or {}
    items = validate_meal_items(data.get("items"))
    return get_food_table().estimate_meal(items), items


@meals_api.post("/meals/estimate")
def estimate_meal():
    estimate, _ = _estimate_from_request()
    return ok({"estimate": estimate})


@meals_api.post("/meals")
def log_meal():
    estimate, _ = _estimate_from_request()
    data = request.get_json(silent=True) or {}
    totals = estimate["totals"]
    log = MealLog(
        user_id=current_user_id(),
        meal_type=validate_meal_type(data.get("meal_type")),
        raw_text=(sanitize_text(data["raw_text"], max_chars=2000, field="raw_text")
                  if data.get("raw_text") else None),
        items=estimate["items"],
        calories=totals["calories"],
        protein_g=totals["protein_g"],
        fat_g=totals["fat_g"],
        carbs_g=totals["carbs_g"],
        fiber_g=totals["fiber_g"],
    )
    db.session.add(log)
    db.session.commit()
    return ok({"meal": log.to_dict(), "unmatched": estimate["unmatched"]}, 201)


@meals_api.get("/meals")
def list_meals():
    days = int(validate_range(request.args.get("days", 7), "days", 1, 90))
    return ok({"meals": [m.to_dict()
                         for m in MealLog.since(days, current_user_id())]})


@meals_api.delete("/meals/<int:meal_id>")
def delete_meal(meal_id: int):
    log = db.session.get(MealLog, meal_id)
    # Same 'does not exist' response for another user's row as for a missing
    # one: a distinct 403 would confirm the id is real and let anyone map out
    # which records exist by probing.
    if log is None or log.user_id != current_user_id():
        raise ValidationError(f"Meal log {meal_id} does not exist.")
    db.session.delete(log)
    db.session.commit()
    return ok({"deleted": meal_id})


@meals_api.get("/foods/search")
def search_foods():
    query = request.args.get("q", "")
    results = get_food_table().search(query)
    return ok({"results": [
        {"name": f.name, "serving_desc": f.serving_desc, "calories": f.calories,
         "protein_g": f.protein_g, "category": f.category, "cuisine": f.cuisine}
        for f in results
    ]})


@meals_api.get("/meal-plans")
def list_meal_plans():
    rows = db.session.execute(
        db.select(MealPlan).where(MealPlan.user_id == current_user_id())
        .order_by(MealPlan.created_at.desc()).limit(50)
    ).scalars()
    return ok({"plans": [p.to_dict(include_plan=False) for p in rows]})


@meals_api.get("/meal-plans/<int:plan_id>")
def get_meal_plan(plan_id: int):
    """Full detail of one saved plan (used by the planner page)."""
    plan = db.session.get(MealPlan, plan_id)
    if plan is None or plan.user_id != current_user_id():
        raise ValidationError(f"Meal plan {plan_id} does not exist.")
    return ok({"plan": plan.to_dict()})


@meals_api.get("/export/meal-plan/<int:plan_id>.pdf")
def export_meal_plan(plan_id: int):
    """Download a saved plan as a branded PDF (see services/export_service)."""
    from flask import Response

    from nutrimind.models import UserProfile
    from nutrimind.services.export_service import build_meal_plan_pdf

    plan = db.session.get(MealPlan, plan_id)
    if plan is None or plan.user_id != current_user_id():
        raise ValidationError(f"Meal plan {plan_id} does not exist.")
    pdf_bytes = build_meal_plan_pdf(plan, UserProfile.for_user(current_user_id()))
    filename = f"nutrimind-plan-{plan_id}.pdf"
    return Response(pdf_bytes, mimetype="application/pdf", headers={
        "Content-Disposition": f'attachment; filename="{filename}"'})


@meals_api.delete("/meal-plans/<int:plan_id>")
def delete_meal_plan(plan_id: int):
    plan = db.session.get(MealPlan, plan_id)
    if plan is None or plan.user_id != current_user_id():
        raise ValidationError(f"Meal plan {plan_id} does not exist.")
    db.session.delete(plan)
    db.session.commit()
    return ok({"deleted": plan_id})
